name: Run Login Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */3 * *"  # 每三天运行一次
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 使用稳定的 Python 3.10

      - name: 安装 Chrome 和 ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          chrome_version=$(google-chrome --version | awk '{print $3}')
          wget -q "https://chromedriver.storage.googleapis.com/${chrome_version%.*.*}/chromedriver_linux64.zip"
          sudo unzip -o chromedriver_linux64.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm chromedriver_linux64.zip

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests

      - name: 运行登录脚本
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        run: |
          python login_script.py

      - name: 上传截图
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: login-screenshots
          path: "*.png"
          retention-days: 7

  keepalive-workflow:
    name: Keepalive Workflow
    needs: login
    if: always()
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
